# Generated by Django 2.0.7 on 2019-02-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produce_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='produce_time1',
        ),
    ]
